import Link from "next/link";
import { randomUUID } from "node:crypto";
import { activateHostedAuthorityRequestAction, reissueParticipantInvitationAction } from "@/app/account-actions";
import { EditDraftEmailsForm } from "./EditDraftEmailsForm";
import { mayProvisionDemoRun } from "@/lib/authority/demo-boundary";
import { canRecordAuthorityDecision, canReviewAuthorityEvidence, requestCoordinatorRecoveryMessage } from "@/lib/authority/role-capabilities";
import { HOSTED_ACTIONS, hostedStatusLabel } from "@/lib/authority/hosted-records";
import { hostedDecisionLabel, mapHostedInstitutionDecision } from "@/lib/authority/hosted-decisions";
import { hostedRequestNoticeMessage } from "@/lib/authority/hosted-request-notice";
import { canReissueParticipantAccess, participantAccessPurpose } from "@/lib/authority/participant-resume";
import { buildCaseOrientation, buildDocumentReviewModel } from "@/lib/authority/orientation-strip";
import styles from "@/components/app/app-shell.module.css";
import { MultiInstitutionOriginBadge } from "@/components/app/MultiInstitutionOriginBadge";
import { OrientationStrip } from "@/components/app/OrientationStrip";
import { DocumentReviewStrip } from "@/components/app/DocumentReviewStrip";
import { CopyAccessLink } from "./CopyAccessLink";
import { HostedAuthorityRequestLower } from "./HostedAuthorityRequestLower";
