-- passage_private.can_manage_location() is called from the partner_organizations
-- RLS SELECT policy (partner_organizations_visible_select), but authenticated
-- was never granted EXECUTE on it, unlike its sibling
-- is_active_partner_member_for(). Any query that touches partner_members
-- (which embeds partner_organizations) fails with 42501 "permission denied
-- for function can_manage_location" for every user, including one with zero
-- partner_members rows -- Postgres checks function grants for every object
-- referenced by the rewritten query, not just rows actually returned. Found
-- live: /partner/start (vendor self-serve signup) was completely dead for
-- every account. SECURITY DEFINER, scoped internally to auth.uid(), matching
-- the existing safe grant pattern.
grant execute on function passage_private.can_manage_location(uuid, uuid) to authenticated;
